name: recipe_finder_app
description: "Find random recipes on your fingertips"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  meta: ^1.17.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  logger: ^2.5.0
  hive: ^2.2.3
  get_it: ^9.2.0
  equatable: ^2.0.8
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  shimmer_animation: ^2.2.1
  flutter_keyboard_visibility: ^6.0.0
  widget_zoom: ^0.0.4
  youtube_player_flutter: ^9.1.3
  flutter_statusbarcolor_ns: ^0.6.0
  flutter_native_splash: ^2.4.7
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - asset/icon/
    - asset/Plus Jakarta Sans/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-Regular.ttf
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: asset/Plus Jakarta Sans/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

flutter_native_splash:
  color: "#FFFBFE"
  color_dark: "#1C1B1F"
  fullscreen: true
  
  android_12:
    color: "#FFFBFE"
    color_dark: "#1C1B1F"

